---
- name: Deploy Prometheus and Grafana to K3s
  hosts: localhost
  become: false
  tasks:
    - name: Apply Prometheus Deployment
      kubernetes.core.k8s:
        kubeconfig: "~/.kube/config"
        state: present
        src: "../k8s/prometheus-deployment.yaml"

    - name: Apply Grafana Deployment
      kubernetes.core.k8s:
        kubeconfig: "~/.kube/config"
        state: present
        src: "../k8s/grafana-deployment.yaml"

    - name: Apply Common Service
      kubernetes.core.k8s:
        kubeconfig: "~/.kube/config"
        state: present
        src: "../k8s/service.yaml"
