---
- name: Install K3s on node
  shell: |
    curl -sfL https://get.k3s.io | sh -
  become: yes

- name: Copy kubeconfig file for K3s
  copy:
    src: /final/portfolio/kubeconfig.yaml
    dest: /etc/rancher/k3s/k3s.yaml
  become: yes
