---
- name: Create namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: portfolio
    state: present

- name: Deploy Portfolio app to K3s
  k8s:
    kubeconfig: /path/to/kubeconfig
    state: present
    definition: /final/portfolio/ansible/k8s/deployment.yaml

- name: Expose service
  kubernetes.core.k8s:
    state: present
    namespace: portfolio
    src: "{{ playbook_dir }}/../../k8s/service.yaml"
