- name: Copy Dockerfile
  copy:
    src: /final/portfolio/Dockerfile
    dest: /tmp/Dockerfile

- name: Copy portfolio HTML, CSS, JS files
  copy:
    src: /final/portfolio/
    dest: /tmp/portfolio/
    mode: 0755

- name: Build Docker image for portfolio
  community.docker.docker_image:
    name: my-portfolio
    tag: latest
    build:
      path: /tmp
      dockerfile: Dockerfile
    state: present
