- name: Create folder for portfolio website only
  file:
    path: /tmp/portfolio
    state: directory

- name: Copy static portfolio files using rsync (excluding sensitive dirs)
  ansible.builtin.synchronize:
    src: /final/portfolio/
    dest: /tmp/portfolio/
    rsync_opts:
      - "--exclude=ansible"
      - "--exclude=.github"
      - "--exclude=k8s"
      - "--exclude=monitoring"
      - "--exclude=Jenkinsfile"
      - "--exclude=Dockerfile"
      - "--exclude=*.yaml"
      - "--exclude=venv"
      - "--exclude=__pycache__"


