- name: Create namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: portfolio
    state: present

- name: Deploy Portfolio app to K3s
  kubernetes.core.k8s:
    kubeconfig: /var/lib/jenkins/.kube/config
    state: present
    definition: "{{ playbook_dir }}/../../k8s/deployment.yaml"

- name: Expose service
  kubernetes.core.k8s:
    state: present
    namespace: portfolio
    src: "{{ playbook_dir }}/../../k8s/service.yaml"
