- name: Deploy Portfolio app to K3s
  hosts: localhost
  tasks:
    - name: Create namespace
      k8s_namespace:
        name: portfolio
        state: present

    - name: Deploy Portfolio app to K3s
      kubernetes:
        state: present
        definition: "{{ lookup('file', 'k8s/deployment.yaml') }}"
