---
- name: Deploy the portfolio application
  hosts: localhost
  become: yes
  roles:
    - docker
    - deploy_app
    - k3s

  tasks:
    - name: Build Docker image for portfolio
      community.docker.docker_image:
        name: my-portfolio
        tag: latest
        build:
          path: /tmp/portfolio
          dockerfile: Dockerfile
        source: build
        state: present

    - name: Run Docker container for portfolio app
      docker_container:
        name: portfolio-container
        image: my-portfolio:latest
        state: started
        ports:
          - "80:80"
